### ISSUE TITLE
Don't use Encoding.ASCII

### ISSUE THREAD

**Issue by CodesInChaos** [ssg/HashDepot#1]
`Encoding.ASCII` silently corrupts the input if it contains characters outside the ASCII range. One consequence of this is that all non ASCII strings of equal length will have the same hash. This enables the very HashDoS SipHash was designed to prevent.

You could UTF-8 `new UTF8Encoding(false, true)` or UTF-16 `new UnicodeEncoding(false,false, true)` instead. Note that `Encoding.Utf8` and `Encoding.Unicode` suffer from similar corruption as `Encoding.ASCII` if the string is invalid, so they shouldn't be used either.

Alternatively you could manually convert each `char` to two bytes, which you feed to SipHash. Or combine four `char`s to a 64 bit integer and feed it to SipHash directly, bypassing the conversion to bytes directly. These approaches have the property that they won't throw exceptions when operating on invalid strings.

**Comment by ssg** [comment]
Thanks those were just examples to simply explain the point, I didn't want to confuse user with encoding semantics. Do you think it would mislead developers?

**Comment by ssg** [comment]
Closing per my explanation.
