### ISSUE TITLE
Optimise dependencies based on TFM

### ISSUE THREAD

**Issue by thompson-tomo** [ssg/HashDepot#10]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
Atleast 1 if not both the dependencies can be removed as they are provided via the framework.

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by ssg** [comment]
Which dependency do you mean?

**Comment by thompson-tomo** [comment]
@ssg In the end, it ended up being both dependencies are able to be provided by the framework see #11

**Comment by ssg** [comment]
Please be more specific. What problem does removing that dependency solve?

**Comment by thompson-tomo** [comment]
it does 2 things, reduce compilation size and reduces chance of CVE's/conflicting versions. Think of those dependencies like System.IO you don't need to add that package if you want access to the file system due to the framework already guranteeing tha the library will be available.
