### ISSUE TITLE
Implement awareness for big-endian systems

### ISSUE THREAD

**Issue by RenzoCoppola** [ssg/HashDepot#2]
Would these hash functions give me different results in different machines with different endianness?

**Comment by ssg** [comment]
Good question. I don't have tests for endianness and definitely haven't written the code with endianness in mind. I only tested it on little endian. Let me check this out.

**Comment by ssg** [comment]
I checked this out (finally), SipHash and MurmurHash seem to be endianness sensitive. Fnv1 and Fnv1a should be okay. Changes needed to make them endian-aware.

**Comment by ssg** [comment]
Self-note: BitConverter.ToXIntYY() methods actually take endianness into account. So, as long as you use those endianness shouldn't be an issue.

**Comment by ssg** [comment]
This shouldn't be an issue anymore as the library's using .NET's bit conversion algo now.
