### ISSUE TITLE
Updated Nuget package for .NET Standard

### ISSUE THREAD

**Issue by xlegalles** [ssg/HashDepot#3]
Would it be possible to have an updated Nuget package for the v2.0? Mainly because it is .NET standard.
Thank you

**Comment by ssg** [comment]
Hi, it's already .NET Standard (1.3, which is 2.0 compatible). What problems are you having with the latest version? Thanks.

**Comment by xlegalles** [comment]
Yes I saw it. But the Nuget package [available on Nuget.org](https://www.nuget.org/packages/HashDepot/1.2.0) is v1.2. Could you update it to v2.0?
Thx

**Comment by ssg** [comment]
That’s the package version, not the .NET standard version. Why do you need 2.0 at the moment?

**Comment by xlegalles** [comment]
The actual package v1.2 has been published in 2016 and **is not** .NET standard, am I wrong? So I would like you to publish the last version of your development, available on github, which **is** .NET standard compatible. The .NET standard version you use is totally appropriate, this is not the question.
i.e. I don't want to clone your repo locally to use it. I want to use Nuget.org as everybody does usually.

**Comment by ssg** [comment]
oh you're right. i didn't notice the last version wasn't compatible with .NET Standard, got it.

**Comment by ssg** [comment]
this is out now, thanks!
