### ISSUE TITLE
Inconsistent conversion results

### ISSUE THREAD

**Issue by evi1ox** [ssg/HashDepot#5]
There is an inconsistent calculation result, the reason is because `\n`, help!

- c# eg:
```
var buffer = Encoding.UTF8.GetBytes("hello world\ntest test\ntest\n");
uint result = MurmurHash3.Hash32(buffer, 0);
Console.WriteLine(result);
```

- result
```
4126987925
```

- python eg:
```
In [16]: mmh3.hash('hello world\ntest test\ntest\n')
Out[16]: -167979371
```

- result
```
-167979371
```

**Comment by ssg** [comment]
`mm3.hash` returns a signed integer while Hash32 returns unsigned int. You can have the same result by casting Hash32's result to int:

`int result = (int)MurmurHash3.Hash32(...);`

**Comment by evi1ox** [comment]
Thank you very much, one more question

about shodan icon hash encrypt , The following is the operation project

Get icon file bytes -> do base64encode -> use mm3h encryption


```
static void Main(string[] args)
        {
            var data = GetHttpResponse("http://www.baidu.com/favicon.ico");
            var data2 = Convert.ToBase64String(data, Base64FormattingOptions.InsertLineBreaks);
            var buffer = Encoding.UTF8.GetBytes(data2);
            int result = (int)MurmurHash3.Hash32(buffer);
            Console.WriteLine(result);
        }

public static byte[] GetHttpResponse(string url)
        {
            HttpWebRequest myRequest = (HttpWebRequest)WebRequest.Create(url);
            myRequest.Method = "GET";
            WebResponse myResponse = myRequest.GetResponse();
            MemoryStream ms = new MemoryStream();
            myResponse.GetResponseStream().CopyTo(ms);
            byte[] data = ms.ToArray();
            return data;
        }
```


C# Result

```
1251311336
```

python3 Result

```
-1588080585
```

**Comment by ssg** [comment]
@evi1ox Can you share encoded text files? It's possible that either Python encoder doesn't put newlines in the output or the newlines are different between C# and Python (CRLF vs LF).

**Comment by ssg** [comment]
No need, I was able to repro this locally. Python encoder doesn't insert any line breaks. Please make sure Base64 encoders use the same output format. The difference is caused by Base64 differences, not the hash function.

**Comment by evi1ox** [comment]
Yeah, thank you for reminding me, I found it was a base64 problem, and I am considering how to solve it
